const guide =  {"getUpload": {
    "text": "Hello there! To start, please input an image of a face. Or, read through the background information on the left!",
    "speed": 20,
    "eraseDelay": 10000000,
    "typingDelay": 0,
    "eraseSpeed": 30},
"Uploading": {"text": "Loading...this might take a while...", 
    "speed": 20,
    "eraseDelay": 1000,
    "typingDelay": 100,
    "eraseSpeed": 30},
"Uploaded": {"text": "Your results are out! Is this what you expected?", 
    "speed": 20,
    "eraseDelay": 10000000,
    "typingDelay": 100,
    "eraseSpeed": 30},
"Input": {"text": "Sorry! This page is in construction.", 
    "speed": 20,
    "eraseDelay": 10000000,
    "typingDelay": 100,
    "eraseSpeed": 30},
"Analysis": {"text": "Here is what our model focused on with respect to our predictions.", 
"speed": 20,
"eraseDelay": 10000000,
"typingDelay": 100,
"eraseSpeed": 30},

"bias": {"text": "We mentioned in the last slide that biased data yields considerable effects in a model. Here's what our model sees when given biased data vs. unbiased data. Hover over the images to read their captions!", 
"speed": 10,
"eraseDelay": 10000000,
"typingDelay": 100,
"eraseSpeed": 30},
"conclusion": {"text": "And...that's a wrap. Thanks for visiting - we hope you were able to get some insight into how machine learning for facial analysis tools see you!", 
"speed": 10,
"eraseDelay": 10000000,
"typingDelay": 100,
"eraseSpeed": 30}

};

export default {guide};